### ISSUE TITLE
[Feature] Add walletless integration

### ISSUE THREAD

**Issue by Sigri44** [RealToken-Community/dashboard-v2#16]
Create a route type /walletless/xxxxxxxxxxxxxxx (where xxxxxxxx = hash).
We'd link up with RealT to have a common hash pass (in the .env), so we can retrieve the public address from the hash.
Why would we do this? Because in Walletless, the address must never be communicated to the client. In this case, plan to display something like "Walletless" instead of the address in the top right-hand corner.

**Comment by NandyBa** [comment]
We need to have more information about the wallet less. To address this feature
Yet It's can be a good one to implement

**Comment by Sigri44** [comment]
I archive that, no need more with AA implementation.

**Comment by NandyBa** [comment]
> I archive that, no need more with AA implementation.
Will be the same with abstract account, we will need to provide a way fore user to see the dashboard but not the address linked with their AA
