### ISSUE TITLE
[Feature] - Support of ens domain

### ISSUE THREAD

**Issue by NandyBa** [RealToken-Community/dashboard-v2#18]
I propose the addition of Ethereum Name Service (ENS) domain address support in our RealT Community Dashboard. This feature would allow users to input human-readable ENS domain addresses (like `example.eth`) instead of the traditional hexadecimal Ethereum addresses, improving user experience by offering a more intuitive way to interact with blockchain addresses.

### Benefits:
**User-Friendly**: Provides a human-readable and memorizable address format, improving user interaction and experience.

### Proposed Implementation:
1. **ENS Resolution Integration**: Develop and integrate a service to resolve ENS domains to their corresponding Ethereum addresses.
2. **Address Input Update**: Modify address input fields throughout the dashboard to accept and validate ENS domains.
3. **Error Handling**: Implement error messages for invalid or unregistered ENS domains.

**Comment by NandyBa** [comment]
The is two ways to resolves this issue.
- First updating [@realt-interface-commons](https://github.com/real-token/realt-interface-commons/pull/4). But it's require fixing #33
- by implementing a ENS resolver

**Comment by jycssu-com** [comment]
[@realt-interface-commons](https://github.com/real-token/realt-interface-commons/pull/4) was updated to v1.4.6 and should includes ENS resolver
