### ISSUE TITLE
RealT dashboard in Umbrel AppStore ?

### ISSUE THREAD

**Issue by anthony-robin** [RealToken-Community/dashboard-v2#20]
[Umbrel](https://umbrel.com) is an OS that runs on Raspberry PI allowing to locally self-host many open source applications available on the [Umbrel AppStore](https://apps.umbrel.com/).

A motivation to integrate the RealT dashboard would be better privacy regarding users personal informations (wallet address, wallet connect ...).

For example, [Rotki](https://rotki.com) allows users to manage all their different crypto wallets addresses into one application focusing on privacy by having their application [available](https://apps.umbrel.com/app/rotki) on the Umbrel AppStore.

What do you think about this idea for the RealT dashboard ? Do you think it could be worth considering one day ?
I personally would love to have this option and would feel more confident regarding my wallet address or wallet connect not leaking any sensitive information !

Thank you :)

**Comment by NandyBa** [comment]
More than 10 months without new message, so I archive this conversation
