### ISSUE TITLE
[Fix] Fix dependabot vulnerabilities

### ISSUE THREAD

**Issue by Sigri44** [RealToken-Community/dashboard-v2#40]
Last scan give up some vulnerabilities :

https://github.com/RealToken-Community/dashboard-v2/security/dependabot

Thx !

**Comment by Kurtisone** [comment]
Dead link @Sigri44

**Comment by Sigri44** [comment]
> Dead link @Sigri44

Hum invalid rights indeed

<img width="960" alt="image" src="https://github.com/RealToken-Community/dashboard-v2/assets/9304947/d75c9b6b-5a2b-416e-b8a3-5c0550079a7b">

**Comment by NandyBa** [comment]
> Dead link @Sigri44

Link is not dead. It's require you to be logged in

**Comment by Kurtisone** [comment]
Doesn´t work from Github Mobile I guess

**Comment by jycssu-com** [comment]
Everything should be fixed now on the develop branch
