### ISSUE TITLE
Dashboard does not display properties and valuation

### ISSUE THREAD

**Issue by NandyBa** [RealToken-Community/dashboard-v2#41]
I just checkout develop and get this issue.
<img width="1450" alt="Capture d’écran 2024-06-08 à 20 31 50" src="https://github.com/RealToken-Community/dashboard-v2/assets/11545946/309a3ae6-176a-41de-abbc-ff2eb2f5e34f">
Do you have the same ?

**Comment by jycssu-com** [comment]
Yes, I have updated the subgraphs for use the decentralized network. Check the ReadMe, a new environment variable is required for use the decentralized subgraphs, and you need a thegraph account for generated an Api key

**Comment by NandyBa** [comment]
Thanks @jycssu-com

**Comment by NandyBa** [comment]
Working well
Note: this is not a good practice to close issue without looking confirmation or delay of not response.
