### ISSUE TITLE
[Suggestion] Max Yield Indicator

### ISSUE THREAD

**Issue by jojodunet** [RealToken-Community/dashboard-v2#51]
Hello Devs,

Is it possible to add a new indicator that calculates the global yield if all properties are 100% rented and/or if all rent start dates have already begun? 

This indicator should correspond to the existing 'real-time' or 'global' parameter in the menu.

- For the 'real-time' parameter, calculate the maximum yield assuming that all properties are fully rented (excluding priorities for which the rent start date has not started).
- For the ‘global’ parameter, calculate the maximum yield by assuming that all properties are fully rented and all rent start dates have already begun.

The goal of this new indicator is to determine the maximum yield for our portfolio in both scenarios. 
Additionally, it could be useful for portfolio management decisions.

Thank you in advance for considering this request and for the work you have already done.

Best regards.

**Comment by NandyBa** [comment]
Hey @jojodunet, how do you determine the yield for the fully rented property ?
For example if a property have 5 / 6 rented unit and a 3% yield how do you consider the yield for fully rented ? I mean when no-rented there still have cost like insurance

**Comment by jojodunet** [comment]
> Hey @jojodunet, how do you determine the yield for the fully rented property ?
> For example if a property have 5 / 6 rented unit and a 3% yield how do you consider the yield for fully rented ? I mean when no-rented there still have cost like insurance

Can the information be retrieved?

For example Cryptalloc retrieves the information, so the data is available somewhere.

![15C302DA-0BA6-4028-944A-B792D8F7A2C7](https://github.com/RealToken-Community/dashboard-v2/assets/65983141/9de2af48-3000-4abd-a5b6-2a1de155776b)

**Comment by NandyBa** [comment]
@jojodunet that the before rent not exactly the future rent

**Comment by NandyBa** [comment]
We maybe use it as estimation. Yet it's a estimation.
Do we need to consider the last yield with full rent ?
What to consider if property have never been rent ?

**Comment by jojodunet** [comment]
> Do we need to consider the last yield with full rent ?
> What to consider if property have never been rent ?

Do we need to consider the last yield with full rent ? => Yes, exactly the last one

What to consider if property have never been rent ? => if the above data is not available, I would recommend to take the RealT estimated yield at the property sales launch.
